[tool.poetry]
name = "query-generator"
version = "0.1.0"
description = ""
authors = ["Alex Alonso <alejandro.alonso@thedotcollective.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
